Repository loathers/autoscend, pull requests merged in 2020-07, with the labels that each got.

#462 add Mosquito as the absolute default failover for regen familiars
  BUILD/familiars/regen.dat
  RELEASE/data/autoscend_familiars.txt
Labels: bug

#465 Resoration changes to address wasting meat on NPC items when skills are available and MP is in abundance
  RELEASE/data/autoscend_restoration.txt
  RELEASE/scripts/autoscend/auto_restore.ash
  RELEASE/scripts/autoscend/auto_util.ash
  RELEASE/scripts/autoscend/autoscend_header.ash
Labels: bug

#467 Don't waste clovers if we have enough A-boo Clues to complete the peak
  RELEASE/scripts/autoscend/quests/level_9.ash
Labels: bug

#469 add the melodramedary to stat and regen familiars
  BUILD/familiars/regen.dat
  BUILD/familiars/stat.dat
  RELEASE/data/autoscend_familiars.txt
Labels: enhancement

#466 roll out automated mining for trapper ore to all (no longer public beta)
  BUILD/settings/any.dat
  RELEASE/data/autoscend_settings.txt
  RELEASE/scripts/autoscend/auto_choice_adv.ash
  RELEASE/scripts/autoscend/auto_deprecation.ash
  RELEASE/scripts/autoscend/autoscend_header.ash
  RELEASE/scripts/autoscend/quests/level_8.ash
Labels: enhancement

#476 fix MCD flip flopping when not set to max (e.g. Orc Chasm).
  RELEASE/scripts/autoscend/auto_util.ash
Labels: bug

#478 fix lynyrd protestors amount calculating less than it should
  RELEASE/scripts/autoscend/quests/level_11.ash
Labels: bug

#479 Don't farm ores if we have a mountain man trapped in the chateau painting
  RELEASE/scripts/autoscend/quests/level_8.ash
Labels: bug

#480 couple of tweaks to consumption
  RELEASE/scripts/autoscend/auto_cooking.ash
Labels: enhancement

#484 Better handling for offhand/familiar equip/familiar in desert (+ supp…
  RELEASE/scripts/autoscend/quests/level_11.ash
Labels: enhancement

#494 fix ProvidePlusNonCombat not inverting the return value from numeric_modifier()
  RELEASE/scripts/autoscend/auto_util.ash
Labels: bug

#495 fix ProvidePlusNonCombat not inverting the return value from numeric_modifier() (#494)
  RELEASE/scripts/autoscend/auto_util.ash
Labels: bug

#496 add Invisible Avatar to buffmaintain
  RELEASE/scripts/autoscend/auto_util.ash
Labels: bug

#497 add Invisible Avatar to buffmaintain
  RELEASE/scripts/autoscend/auto_util.ash
Labels: bug

#500 fix non-adventure.php adventure handling and more.
  RELEASE/scripts/autoscend.ash
  RELEASE/scripts/autoscend/auto_adventure.ash
  RELEASE/scripts/autoscend/auto_choice_adv.ash
  RELEASE/scripts/autoscend/auto_deprecation.ash
  RELEASE/scripts/autoscend/auto_equipment.ash
  RELEASE/scripts/autoscend/auto_pre_adv.ash
  RELEASE/scripts/autoscend/autoscend_header.ash
  RELEASE/scripts/autoscend/iotms/mr2017.ash
  RELEASE/scripts/autoscend/iotms/mr2018.ash
  RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash
  RELEASE/scripts/autoscend/paths/low_key_summer.ash
  RELEASE/scripts/autoscend/quests/level_10.ash
  RELEASE/scripts/autoscend/quests/level_11.ash
  RELEASE/scripts/autoscend/quests/level_8.ash
Labels: bug

#501 Misc Ed fixes
  RELEASE/scripts/autoscend/auto_choice_adv.ash
  RELEASE/scripts/autoscend/auto_combat.ash
  RELEASE/scripts/autoscend/auto_cooking.ash
  RELEASE/scripts/autoscend/auto_equipment.ash
  RELEASE/scripts/autoscend/auto_pre_adv.ash
  RELEASE/scripts/autoscend/auto_util.ash
  RELEASE/scripts/autoscend/autoscend_header.ash
  RELEASE/scripts/autoscend/iotms/mr2019.ash
  RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash
  RELEASE/scripts/autoscend/quests/level_11.ash
  RELEASE/scripts/autoscend/quests/level_7.ash
  RELEASE/scripts/autoscend/quests/level_any.ash
Labels: bug, enhancement

#504 Couple of small bug fixes.
  RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash
  RELEASE/scripts/autoscend/quests/level_11.ash
  RELEASE/scripts/autoscend/quests/level_12.ash
Labels: bug

#514 Mushroom Garden and Guzzlr handling
  RELEASE/scripts/autoscend.ash
  RELEASE/scripts/autoscend/auto_zone.ash
  RELEASE/scripts/autoscend/iotms/mr2020.ash
Labels: enhancement
